eureka:
  client:
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8576/eureka/
  instance:
    hostname: localhost
#NOTE: Below variable names is user defined, so it can any kind
microservices:
  payment-service:
    endpoints:
      endpoint:
        dopayuri:  http://PAYMENT-SERVICE/payment/doPayment
        dopayupi:  http://PAYMENT-SERVICE/payment/doUpi
  order-service:
    endpoints:
      endpoint:
        bookOrderuri:  http://ORDER-SERVICE/order/bookOrder
spring:
  zipkin:
    base-url: http://localhost:9411/
