eureka:
  client:
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8576/eureka/
  instance:
    hostname: localhost

microservices:
  payment-serivice:
    endpoints:
      endpoint:
        uri:  http://PAYMENT-SERVICE/payment/doPayment
  order-serivice:
    endpoints:
      endpoint:
        uri:  http://ORDER-SERVICE/order/bookOrder
spring:
  zipkin:
    base-url: http://localhost:9411/
